meson fixes
lz4/lz4 pull request #1155
Opened 2022-09-03 03:44 UTC by neheb

2022-09-05 12:24 UTC, eli-schwartz requested changes

2022-09-05 12:24 UTC, eli-schwartz commented on contrib/meson/meson/lib/meson.build
> -  version: lz4_version,
This is not how versions work, you *must* opt in to soname/version. The kwarg is crucial.

2022-09-14 18:42 UTC, tristan957 commented
Why are you doing this when I have an open PR already?

2022-09-17 17:28 UTC, neheb commented
Feel free to fold any changes here to your PR.

2022-11-16 05:15 UTC, closed without merging